name: search
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: "none"
environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

  dartz: ^0.10.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  get_it: ^7.1.3
  path_provider: ^2.0.2
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^9.0.2
flutter:
