// Mocks generated by Mockito 5.0.17 from annotations
// in core/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i9;
import 'dart:convert' as _i42;
import 'dart:typed_data' as _i43;

import 'package:core/core.dart' as _i13;
import 'package:core/data/datasources/db/database_helper.dart' as _i8;
import 'package:core/data/datasources/movies/movie_local_data_source.dart'
    as _i18;
import 'package:core/data/datasources/movies/movie_remote_data_source.dart'
    as _i16;
import 'package:core/data/datasources/tv_shows/tv_show_local_data_source.dart'
    as _i23;
import 'package:core/data/datasources/tv_shows/tv_show_remote_data_source.dart'
    as _i21;
import 'package:core/data/models/movies/movie_detail_model.dart' as _i3;
import 'package:core/data/models/movies/movie_model.dart' as _i17;
import 'package:core/data/models/movies/movie_table.dart' as _i11;
import 'package:core/data/models/tv_shows/tv_show_detail_model.dart' as _i4;
import 'package:core/data/models/tv_shows/tv_show_model.dart' as _i22;
import 'package:core/data/models/tv_shows/tv_show_table.dart' as _i12;
import 'package:core/domain/entities/movies/movie.dart' as _i14;
import 'package:core/domain/entities/movies/movie_detail.dart' as _i15;
import 'package:core/domain/entities/tv_shows/tv_show.dart' as _i19;
import 'package:core/domain/entities/tv_shows/tv_show_detail.dart' as _i20;
import 'package:core/domain/repositories/movies/movie_repository.dart' as _i5;
import 'package:core/domain/repositories/tv_shows/tv_show_repository.dart'
    as _i6;
import 'package:core/domain/usecases/movies/get_movie_detail.dart' as _i24;
import 'package:core/domain/usecases/movies/get_movie_recommendations.dart'
    as _i25;
import 'package:core/domain/usecases/movies/get_now_playing_movies.dart'
    as _i29;
import 'package:core/domain/usecases/movies/get_popular_movies.dart' as _i30;
import 'package:core/domain/usecases/movies/get_top_rated_movies.dart' as _i31;
import 'package:core/domain/usecases/movies/get_watchlist_movie_status.dart'
    as _i26;
import 'package:core/domain/usecases/movies/get_watchlist_movies.dart' as _i32;
import 'package:core/domain/usecases/movies/remove_watchlist_movie.dart'
    as _i28;
import 'package:core/domain/usecases/movies/save_watchlist_movie.dart' as _i27;
import 'package:core/domain/usecases/tv_shows/get_on_the_air_tv_shows.dart'
    as _i34;
import 'package:core/domain/usecases/tv_shows/get_popular_tv_shows.dart'
    as _i33;
import 'package:core/domain/usecases/tv_shows/get_top_rated_tv_shows.dart'
    as _i35;
import 'package:core/domain/usecases/tv_shows/get_tv_show_detail.dart' as _i36;
import 'package:core/domain/usecases/tv_shows/get_tv_show_recommendations.dart'
    as _i37;
import 'package:core/domain/usecases/tv_shows/get_watchlist_tv_show_status.dart'
    as _i38;
import 'package:core/domain/usecases/tv_shows/get_watchlist_tv_shows.dart'
    as _i41;
import 'package:core/domain/usecases/tv_shows/remove_watchlist_tv_show.dart'
    as _i40;
import 'package:core/domain/usecases/tv_shows/save_watchlist_tv_show.dart'
    as _i39;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i10;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeMovieDetailResponse_1 extends _i1.Fake
    implements _i3.MovieDetailResponse {}

class _FakeTvShowDetailResponse_2 extends _i1.Fake
    implements _i4.TvShowDetailResponse {}

class _FakeMovieRepository_3 extends _i1.Fake implements _i5.MovieRepository {}

class _FakeTvShowRepository_4 extends _i1.Fake implements _i6.TvShowRepository {
}

class _FakeResponse_5 extends _i1.Fake implements _i7.Response {}

class _FakeStreamedResponse_6 extends _i1.Fake implements _i7.StreamedResponse {
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i8.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i10.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i10.Database?>.value())
          as _i9.Future<_i10.Database?>);
  @override
  _i9.Future<int> insertWatchlistMovie(_i11.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlistMovie, [movie]),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> removeWatchlistMovie(_i11.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistMovie, [movie]),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i9.Future<List<Map<String, dynamic>>>);
  @override
  _i9.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i9.Future<Map<String, dynamic>?>);
  @override
  _i9.Future<int> insertWatchlistTvShow(_i12.TvShowTable? tvShow) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlistTvShow, [tvShow]),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<int> removeWatchlistTvShow(_i12.TvShowTable? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlistTvShow, [tvShow]),
          returnValue: Future<int>.value(0)) as _i9.Future<int>);
  @override
  _i9.Future<List<Map<String, dynamic>>> getWatchlistTvShows() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvShows, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i9.Future<List<Map<String, dynamic>>>);
  @override
  _i9.Future<Map<String, dynamic>?> getTvShowById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvShowById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i9.Future<Map<String, dynamic>?>);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i5.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>
      getNowPlayingMovies() => (super.noSuchMethod(
          Invocation.method(#getNowPlayingMovies, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(Invocation.method(#getPopularMovies, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, _i15.MovieDetail>> getMovieDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
          returnValue: Future<_i2.Either<_i13.Failure, _i15.MovieDetail>>.value(
              _FakeEither_0<_i13.Failure, _i15.MovieDetail>())) as _i9
          .Future<_i2.Either<_i13.Failure, _i15.MovieDetail>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>
      getMovieRecommendations(int? id) => (super.noSuchMethod(
          Invocation.method(#getMovieRecommendations, [id]),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> searchMovies(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, String>> saveWatchlist(
          _i15.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i9.Future<_i2.Either<_i13.Failure, String>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, String>> removeWatchlist(
          _i15.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i9.Future<_i2.Either<_i13.Failure, String>>);
  @override
  _i9.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i16.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i17.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingMovies, []),
              returnValue:
                  Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
          as _i9.Future<List<_i17.MovieModel>>);
  @override
  _i9.Future<List<_i17.MovieModel>> getPopularMovies() => (super.noSuchMethod(
          Invocation.method(#getPopularMovies, []),
          returnValue: Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
      as _i9.Future<List<_i17.MovieModel>>);
  @override
  _i9.Future<List<_i17.MovieModel>> getTopRatedMovies() => (super.noSuchMethod(
          Invocation.method(#getTopRatedMovies, []),
          returnValue: Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
      as _i9.Future<List<_i17.MovieModel>>);
  @override
  _i9.Future<_i3.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieDetail, [id]),
              returnValue: Future<_i3.MovieDetailResponse>.value(
                  _FakeMovieDetailResponse_1()))
          as _i9.Future<_i3.MovieDetailResponse>);
  @override
  _i9.Future<List<_i17.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieRecommendations, [id]),
              returnValue:
                  Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
          as _i9.Future<List<_i17.MovieModel>>);
  @override
  _i9.Future<List<_i17.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchMovies, [query]),
              returnValue:
                  Future<List<_i17.MovieModel>>.value(<_i17.MovieModel>[]))
          as _i9.Future<List<_i17.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i18.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> insertWatchlist(_i11.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<String> removeWatchlist(_i11.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i11.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<_i11.MovieTable?>.value())
          as _i9.Future<_i11.MovieTable?>);
  @override
  _i9.Future<List<_i11.MovieTable>> getWatchlistMovies() => (super.noSuchMethod(
          Invocation.method(#getWatchlistMovies, []),
          returnValue: Future<List<_i11.MovieTable>>.value(<_i11.MovieTable>[]))
      as _i9.Future<List<_i11.MovieTable>>);
}

/// A class which mocks [TvShowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowRepository extends _i1.Mock implements _i6.TvShowRepository {
  MockTvShowRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>
      getOnTheAirTvShows() =>
          (super.noSuchMethod(Invocation.method(#getOnTheAirTvShows, []),
                  returnValue:
                      Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                          _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
              as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>> getPopularTvShows() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvShows, []),
              returnValue:
                  Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                      _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
          as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>
      getTopRatedTvShows() =>
          (super.noSuchMethod(Invocation.method(#getTopRatedTvShows, []),
                  returnValue:
                      Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                          _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
              as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, _i20.TvShowDetail>> getTvShowDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvShowDetail, [id]),
              returnValue:
                  Future<_i2.Either<_i13.Failure, _i20.TvShowDetail>>.value(
                      _FakeEither_0<_i13.Failure, _i20.TvShowDetail>()))
          as _i9.Future<_i2.Either<_i13.Failure, _i20.TvShowDetail>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>
      getTvShowRecommendations(int? id) => (super.noSuchMethod(
              Invocation.method(#getTvShowRecommendations, [id]),
              returnValue:
                  Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                      _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
          as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>> searchTvShows(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvShows, [query]),
              returnValue:
                  Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                      _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
          as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, String>> saveWatchlist(
          _i20.TvShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tvShow]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i9.Future<_i2.Either<_i13.Failure, String>>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, String>> removeWatchlist(
          _i20.TvShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvShow]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i9.Future<_i2.Either<_i13.Failure, String>>);
  @override
  _i9.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>
      getWatchlistTvShows() =>
          (super.noSuchMethod(Invocation.method(#getWatchlistTvShows, []),
                  returnValue:
                      Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                          _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
              as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
}

/// A class which mocks [TvShowRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowRemoteDataSource extends _i1.Mock
    implements _i21.TvShowRemoteDataSource {
  MockTvShowRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<List<_i22.TvShowModel>> getOnTheAirTvShows() =>
      (super.noSuchMethod(Invocation.method(#getOnTheAirTvShows, []),
              returnValue:
                  Future<List<_i22.TvShowModel>>.value(<_i22.TvShowModel>[]))
          as _i9.Future<List<_i22.TvShowModel>>);
  @override
  _i9.Future<List<_i22.TvShowModel>> getPopularTvShows() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvShows, []),
              returnValue:
                  Future<List<_i22.TvShowModel>>.value(<_i22.TvShowModel>[]))
          as _i9.Future<List<_i22.TvShowModel>>);
  @override
  _i9.Future<List<_i22.TvShowModel>> getTopRatedTvShows() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvShows, []),
              returnValue:
                  Future<List<_i22.TvShowModel>>.value(<_i22.TvShowModel>[]))
          as _i9.Future<List<_i22.TvShowModel>>);
  @override
  _i9.Future<_i4.TvShowDetailResponse> getTvShowDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvShowDetail, [id]),
              returnValue: Future<_i4.TvShowDetailResponse>.value(
                  _FakeTvShowDetailResponse_2()))
          as _i9.Future<_i4.TvShowDetailResponse>);
  @override
  _i9.Future<List<_i22.TvShowModel>> getTvShowRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvShowRecommendations, [id]),
              returnValue:
                  Future<List<_i22.TvShowModel>>.value(<_i22.TvShowModel>[]))
          as _i9.Future<List<_i22.TvShowModel>>);
  @override
  _i9.Future<List<_i22.TvShowModel>> searchTvShows(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvShows, [query]),
              returnValue:
                  Future<List<_i22.TvShowModel>>.value(<_i22.TvShowModel>[]))
          as _i9.Future<List<_i22.TvShowModel>>);
}

/// A class which mocks [TvShowLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvShowLocalDataSource extends _i1.Mock
    implements _i23.TvShowLocalDataSource {
  MockTvShowLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<String> insertWatchlist(_i12.TvShowTable? tvShow) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [tvShow]),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<String> removeWatchlist(_i12.TvShowTable? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvShow]),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i12.TvShowTable?> getTvShowById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvShowById, [id]),
              returnValue: Future<_i12.TvShowTable?>.value())
          as _i9.Future<_i12.TvShowTable?>);
  @override
  _i9.Future<List<_i12.TvShowTable>> getWatchlistTvShows() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvShows, []),
              returnValue:
                  Future<List<_i12.TvShowTable>>.value(<_i12.TvShowTable>[]))
          as _i9.Future<List<_i12.TvShowTable>>);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i24.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_3()) as _i5.MovieRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, _i15.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i13.Failure, _i15.MovieDetail>>.value(
              _FakeEither_0<_i13.Failure, _i15.MovieDetail>())) as _i9
          .Future<_i2.Either<_i13.Failure, _i15.MovieDetail>>);
}

/// A class which mocks [GetMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendations extends _i1.Mock
    implements _i25.GetMovieRecommendations {
  MockGetMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_3()) as _i5.MovieRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
}

/// A class which mocks [GetWatchlistMovieStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovieStatus extends _i1.Mock
    implements _i26.GetWatchlistMovieStatus {
  MockGetWatchlistMovieStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_3()) as _i5.MovieRepository);
  @override
  _i9.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
}

/// A class which mocks [SaveWatchlistMovie].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistMovie extends _i1.Mock
    implements _i27.SaveWatchlistMovie {
  MockSaveWatchlistMovie() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_3()) as _i5.MovieRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, String>> execute(
          _i15.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i9.Future<_i2.Either<_i13.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistMovie].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistMovie extends _i1.Mock
    implements _i28.RemoveWatchlistMovie {
  MockRemoveWatchlistMovie() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_3()) as _i5.MovieRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, String>> execute(
          _i15.MovieDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i9.Future<_i2.Either<_i13.Failure, String>>);
}

/// A class which mocks [GetNowPlayingMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNowPlayingMovies extends _i1.Mock
    implements _i29.GetNowPlayingMovies {
  MockGetNowPlayingMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_3()) as _i5.MovieRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
}

/// A class which mocks [GetPopularMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularMovies extends _i1.Mock implements _i30.GetPopularMovies {
  MockGetPopularMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_3()) as _i5.MovieRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
}

/// A class which mocks [GetTopRatedMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedMovies extends _i1.Mock implements _i31.GetTopRatedMovies {
  MockGetTopRatedMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MovieRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeMovieRepository_3()) as _i5.MovieRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
}

/// A class which mocks [GetWatchlistMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistMovies extends _i1.Mock
    implements _i32.GetWatchlistMovies {
  MockGetWatchlistMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i14.Movie>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Movie>>())) as _i9
          .Future<_i2.Either<_i13.Failure, List<_i14.Movie>>>);
}

/// A class which mocks [GetPopularTvShows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTvShows extends _i1.Mock implements _i33.GetPopularTvShows {
  MockGetPopularTvShows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                      _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
          as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
}

/// A class which mocks [GetOnTheAirTvShows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTvShows extends _i1.Mock
    implements _i34.GetOnTheAirTvShows {
  MockGetOnTheAirTvShows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                      _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
          as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
}

/// A class which mocks [GetTopRatedTvShows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTvShows extends _i1.Mock
    implements _i35.GetTopRatedTvShows {
  MockGetTopRatedTvShows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                      _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
          as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
}

/// A class which mocks [GetTvShowDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowDetail extends _i1.Mock implements _i36.GetTvShowDetail {
  MockGetTvShowDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, _i20.TvShowDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  Future<_i2.Either<_i13.Failure, _i20.TvShowDetail>>.value(
                      _FakeEither_0<_i13.Failure, _i20.TvShowDetail>()))
          as _i9.Future<_i2.Either<_i13.Failure, _i20.TvShowDetail>>);
}

/// A class which mocks [GetTvShowRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowRecommendations extends _i1.Mock
    implements _i37.GetTvShowRecommendations {
  MockGetTvShowRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
              returnValue:
                  Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                      _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
          as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
}

/// A class which mocks [GetWatchlistTvShowStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvShowStatus extends _i1.Mock
    implements _i38.GetWatchlistTvShowStatus {
  MockGetWatchlistTvShowStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i9.Future<bool>);
}

/// A class which mocks [SaveWatchlistTvShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTvShow extends _i1.Mock
    implements _i39.SaveWatchlistTvShow {
  MockSaveWatchlistTvShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, String>> execute(
          _i20.TvShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvShow]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i9.Future<_i2.Either<_i13.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTvShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTvShow extends _i1.Mock
    implements _i40.RemoveWatchlistTvShow {
  MockRemoveWatchlistTvShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, String>> execute(
          _i20.TvShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#execute, [tvShow]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i9.Future<_i2.Either<_i13.Failure, String>>);
}

/// A class which mocks [GetWatchlistTvShows].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvShows extends _i1.Mock
    implements _i41.GetWatchlistTvShows {
  MockGetWatchlistTvShows() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.TvShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTvShowRepository_4()) as _i6.TvShowRepository);
  @override
  _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
              returnValue:
                  Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>.value(
                      _FakeEither_0<_i13.Failure, List<_i19.TvShow>>()))
          as _i9.Future<_i2.Either<_i13.Failure, List<_i19.TvShow>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i7.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_5()))
          as _i9.Future<_i7.Response>);
  @override
  _i9.Future<_i7.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_5()))
          as _i9.Future<_i7.Response>);
  @override
  _i9.Future<_i7.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i42.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_5()))
          as _i9.Future<_i7.Response>);
  @override
  _i9.Future<_i7.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i42.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_5()))
          as _i9.Future<_i7.Response>);
  @override
  _i9.Future<_i7.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i42.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_5()))
          as _i9.Future<_i7.Response>);
  @override
  _i9.Future<_i7.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i42.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i7.Response>.value(_FakeResponse_5()))
          as _i9.Future<_i7.Response>);
  @override
  _i9.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i9.Future<String>);
  @override
  _i9.Future<_i43.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i43.Uint8List>.value(_i43.Uint8List(0)))
          as _i9.Future<_i43.Uint8List>);
  @override
  _i9.Future<_i7.StreamedResponse> send(_i7.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i7.StreamedResponse>.value(_FakeStreamedResponse_6()))
          as _i9.Future<_i7.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
